import stylistic from "@stylistic/eslint-plugin-js";

export default {
    plugins: {stylistic},
    rules:   {
        "constructor-super":                        ["error"],
        "getter-return":                            ["error"],
        "no-compare-neg-zero":                      ["error"],
        "no-dupe-args":                             ["error"],
        "no-duplicate-case":                        ["error"],
        "no-func-assign":                           ["error"],
        "no-import-assign":                         ["error"],
        "eqeqeq":                                   ["error"],
        "no-unused-vars":                           ["error", {args: "none"}],
        "camelcase":                                ["error"],
        "curly":                                    ["error"],
        "stylistic/array-bracket-newline":          ["error"],
        "stylistic/array-bracket-spacing":          ["error"],
        "stylistic/array-element-newline":          ["error", "consistent"],
        "stylistic/arrow-parens":                   ["error"],
        "stylistic/arrow-spacing":                  ["error"],
        "stylistic/block-spacing":                  ["error"],
        "stylistic/brace-style":                    ["error"],
        "stylistic/comma-dangle":                   ["error", "always-multiline"],
        "stylistic/comma-spacing":                  ["error"],
        "stylistic/comma-style":                    ["error"],
        "stylistic/dot-location":                   ["error", "property"],
        "stylistic/eol-last":                       ["error", "never"],
        "stylistic/function-call-spacing":          ["error"],
        "stylistic/function-paren-newline":         ["error", "never"],
        "stylistic/function-call-argument-newline": ["error", "consistent"],
        "stylistic/indent":                         ["error"],
        "stylistic/key-spacing":                    ["error", {align: "value"}],
        "stylistic/keyword-spacing":                ["error"],
        "stylistic/multiline-ternary":              ["error", "always-multiline"],
        "stylistic/new-parens":                     ["error"],
        "stylistic/no-extra-semi":                  ["error"],
        "stylistic/no-mixed-operators":             ["error"],
        "stylistic/no-mixed-spaces-and-tabs":       ["error"],
        "stylistic/no-multi-spaces":                ["error"],
        "stylistic/no-multiple-empty-lines":        ["error"],
        "stylistic/no-trailing-spaces":             ["error"],
        "stylistic/no-whitespace-before-property":  ["error"],
        "stylistic/object-curly-newline":           ["error"],
        "stylistic/object-curly-spacing":           ["error"],
        "stylistic/padded-blocks":                  ["error", "never"],
        "stylistic/quote-props":                    ["error", "consistent-as-needed"],
        "stylistic/quotes":                         ["error"],
        "stylistic/rest-spread-spacing":            ["error"],
        "stylistic/semi":                           ["error"],
        "stylistic/semi-spacing":                   ["error"],
        "stylistic/semi-style":                     ["error"],
        "stylistic/space-before-blocks":            ["error"],
        "stylistic/space-before-function-paren":    ["error", "never"],
        "stylistic/space-in-parens":                ["error"],
        "stylistic/space-infix-ops":                ["error"],
        "stylistic/space-unary-ops":                ["error"],
        "stylistic/spaced-comment":                 ["error"],
        "stylistic/switch-colon-spacing":           ["error"],
        "stylistic/template-curly-spacing":         ["error"],
    },
};